/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 06 18:47:15 GMT 2016
 */

package se.cag.labs.usermanager.config;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import se.cag.labs.usermanager.config.SwaggerConfig;
import springfox.documentation.spring.web.plugins.Docket;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SwaggerConfig_ESTest extends SwaggerConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SwaggerConfig swaggerConfig0 = new SwaggerConfig();
      Docket docket0 = swaggerConfig0.labApi();
      assertTrue(docket0.isEnabled());
  }
}
