/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 06 18:46:47 GMT 2016
 */

package se.cag.labs.usermanager;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import se.cag.labs.usermanager.ErrorMessage;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ErrorMessage_ESTest extends ErrorMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("");
      String string0 = errorMessage0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("");
      boolean boolean0 = errorMessage0.canEqual(errorMessage0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("6C2@");
      String string0 = errorMessage0.getMessage();
      assertEquals("6C2@", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("rM*]V2<AY1$5");
      errorMessage0.setMessage("ErrorMessage(message=");
      ErrorMessage errorMessage1 = new ErrorMessage("rM*]V2<AY1$5");
      boolean boolean0 = errorMessage0.equals(errorMessage1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage((String) null);
      ErrorMessage errorMessage1 = new ErrorMessage((String) null);
      boolean boolean0 = errorMessage0.equals(errorMessage1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("rM*]V2<AY1$5");
      ErrorMessage errorMessage1 = new ErrorMessage("rM*]V2<AY1$5");
      boolean boolean0 = errorMessage0.equals(errorMessage1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("rM*]V2<AY1$5");
      boolean boolean0 = errorMessage0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("lw}9&k");
      boolean boolean0 = errorMessage0.equals(errorMessage0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage((String) null);
      ErrorMessage errorMessage1 = new ErrorMessage("ErrorMessage(message=null)");
      boolean boolean0 = errorMessage0.equals(errorMessage1);
      assertFalse(errorMessage1.equals((Object)errorMessage0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("rM*]V2<AY1$5");
      errorMessage0.setMessage((String) null);
      errorMessage0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("rM*]V2<AY1$5");
      errorMessage0.hashCode();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("6C2@");
      boolean boolean0 = errorMessage0.canEqual("6C2@");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("6C2@");
      errorMessage0.setMessage((String) null);
      String string0 = errorMessage0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ErrorMessage errorMessage0 = new ErrorMessage("6C2@");
      String string0 = errorMessage0.toString();
      assertEquals("ErrorMessage(message=6C2@)", string0);
  }
}
