/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 06 18:47:40 GMT 2016
 */

package se.cag.labs.usermanager;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;
import se.cag.labs.usermanager.UserManagerApplication;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserManagerApplication_ESTest extends UserManagerApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserManagerApplication userManagerApplication0 = new UserManagerApplication();
      // Undeclared exception!
      try { 
        UserManagerApplication.main((String[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Args must not be null
         //
         assertThrownBy("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserManagerApplication userManagerApplication0 = new UserManagerApplication();
      UserManagerApplication userManagerApplication1 = new UserManagerApplication();
      assertFalse(userManagerApplication1.equals((Object)userManagerApplication0));
      
      UserManagerApplication userManagerApplication2 = new UserManagerApplication();
      UserManagerApplication userManagerApplication3 = new UserManagerApplication();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = ";kP";
      stringArray0[3] = "[+\"XCF-{";
      stringArray0[4] = "@(?Z~\\,u";
      stringArray0[5] = "oNeuf-)3wgmBXZ";
      String string0 = "";
      stringArray0[6] = "";
      // Undeclared exception!
      try { 
        UserManagerApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "use_tccl";
      stringArray0[1] = "9n\"W7/V;";
      stringArray0[2] = "o5#";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "";
      // Undeclared exception!
      try { 
        UserManagerApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "{Ng9}Yz";
      stringArray0[1] = "";
      stringArray0[2] = "A*;/Gl'jm#(]uI^$";
      stringArray0[3] = "WARN: The method ";
      stringArray0[4] = "2l{?$0";
      stringArray0[5] = "r_";
      // Undeclared exception!
      try { 
        UserManagerApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "CPwI bX";
      stringArray0[1] = "aC^e";
      stringArray0[2] = "Operation [getClassLoader] is not supported in jcl-over-slf4j. See also ";
      // Undeclared exception!
      try { 
        UserManagerApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UserManagerApplication userManagerApplication0 = new UserManagerApplication();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "#E<0.0D`}u]~%<";
      String string0 = "org.apache.commons.logging.LogFactory.HashtableImpl";
      stringArray0[1] = "org.apache.commons.logging.LogFactory.HashtableImpl";
      stringArray0[2] = ",ufCc";
      String string1 = "}#O74y`/";
      stringArray0[3] = "}#O74y`/";
      // Undeclared exception!
      try { 
        UserManagerApplication.main(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }
}
